export const services = [
  {
    slug: 'personal-branding',
    title: 'Personal Branding',
    kicker: 'Identity',
    headline: 'Turn Your Expertise Into a Powerful Personal Brand',
    summary:
      'Build a strong and professional identity that represents who you are, what you do, and why people should trust you.',
    cta: 'Build Your Personal Brand',
    image: '/images/portrait-founder.jpg',
    items: [
      'Personal Brand Strategy',
      'Profile & Positioning Strategy',
      'Brand Identity',
      'Professional Bio Development',
      'Social Media Profile Optimization',
      'LinkedIn Personal Branding',
      'Instagram Personal Branding',
      'Content Strategy',
      'Personal Brand Photoshoot Planning',
      'Video Content Strategy',
      'Thought Leadership Content',
      'Reputation Building',
      'Personal Website Development',
      'Media Profile Development',
    ],
    audience:
      'Founders • CEOs • Entrepreneurs • Doctors • Consultants • Coaches • Trainers • Professionals • Creators • Public Personalities',
  },
  {
    slug: 'public-relations',
    title: 'Public Relations',
    kicker: 'Reputation',
    headline: 'Build Visibility. Create Credibility. Strengthen Reputation.',
    summary:
      'Strengthen your reputation and increase your visibility through strategic PR, media communication, and brand positioning.',
    cta: 'Strengthen Your Reputation',
    image: '/images/pr-stage.jpg',
    items: [
      'PR Strategy',
      'Brand Positioning',
      'Media Outreach',
      'Press Release Writing',
      'Press Release Distribution',
      'Media Coverage',
      'Online Reputation Management',
      'Founder / CEO PR',
      'Personal Brand PR',
      'Corporate PR',
      'Event PR',
      'Brand Announcements',
      'Interview Coordination',
      'Media Profile Creation',
      'Crisis Communication Support',
    ],
  },
  {
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    kicker: 'Growth',
    headline: 'Turn Attention Into Business Growth',
    summary:
      'Reach the right audience through social media marketing, content strategy, advertising, and digital campaigns.',
    cta: 'Grow Your Brand Online',
    image: '/images/social-flatlay.jpg',
    approach: 'Strategy → Content → Campaign → Engagement → Conversion → Growth',
    items: [
      'Digital Marketing Strategy',
      'Social Media Management',
      'Instagram Marketing',
      'Facebook Marketing',
      'LinkedIn Marketing',
      'Content Marketing',
      'Social Media Campaigns',
      'Meta Ads',
      'Google Ads',
      'Lead Generation Campaigns',
      'Campaign Planning',
      'Content Calendar',
      'Creative Design',
      'Marketing Analytics',
      'Performance Reports',
    ],
  },
  {
    slug: 'website-development',
    title: 'Website Design & Development',
    kicker: 'Digital Home',
    headline: 'Websites Designed to Build Trust and Generate Business',
    summary:
      'Professional, responsive, modern websites designed to communicate your brand and generate business.',
    cta: 'Start Your Website',
    image: '/images/web-mockup.jpg',
    process: [
      { n: '01', t: 'Discover', d: 'Understand your business, audience, competitors, and objectives.' },
      { n: '02', t: 'Strategy', d: 'Plan website structure, messaging, customer journey, and conversion goals.' },
      { n: '03', t: 'Design', d: 'Create a modern user experience aligned with your brand identity.' },
      { n: '04', t: 'Development', d: 'Develop a fast, responsive, and reliable website.' },
      { n: '05', t: 'Launch', d: 'Testing, optimization, and final deployment.' },
      { n: '06', t: 'Support', d: 'Continuous maintenance and improvements when required.' },
    ],
    items: [
      'Corporate Websites',
      'Personal Branding Websites',
      'Business Websites',
      'Portfolio Websites',
      'Landing Pages',
      'Service Websites',
      'E-Commerce Websites',
      'UI / UX Design',
      'Responsive Website Development',
      'Website Redesign',
      'Website Maintenance',
      'SEO-Friendly Website Structure',
      'Website Content Support',
    ],
  },
  {
    slug: 'video-production',
    title: 'Video Editing & Production',
    kicker: 'Content',
    headline: 'Content That Stops the Scroll',
    summary:
      'Creative videos, reels, promotional content, corporate videos, and social media edits designed to capture attention.',
    cta: 'Create Better Content',
    image: '/images/video-set.jpg',
    approach: 'Concept → Edit → Storytelling → Branding → Final Content',
    items: [
      'Instagram Reels Editing',
      'YouTube Video Editing',
      'Personal Branding Videos',
      'Promotional Videos',
      'Corporate Videos',
      'Interview Videos',
      'Podcast Editing',
      'Event Highlights',
      'Social Media Videos',
      'Short-Form Content',
      'Motion Graphics',
      'Video Ads',
      'Product Videos',
      'Brand Story Videos',
    ],
  },
]

export const process = [
  { n: '01', t: 'Discover', d: 'We understand your goals, audience, challenges, and current brand presence.' },
  { n: '02', t: 'Strategize', d: 'We create a clear branding and communication strategy.' },
  { n: '03', t: 'Create', d: 'Our team develops content, campaigns, designs, videos, and digital experiences.' },
  { n: '04', t: 'Launch', d: 'We take your brand and campaigns to the right platforms and audience.' },
  { n: '05', t: 'Grow', d: 'We analyze performance, improve the strategy, and continue building your presence.' },
]

export const differentiators = [
  { t: 'Strategy First', d: 'Every project starts with understanding your goals and audience.' },
  { t: 'Personalized Approach', d: "We don't believe in one-size-fits-all branding." },
  { t: 'Creative Storytelling', d: 'We turn ideas, expertise, and businesses into compelling stories.' },
  { t: 'Complete Digital Ecosystem', d: 'Branding, PR, marketing, websites, and video under one team.' },
  { t: 'Growth Focused', d: 'Our work is designed not just to look good but to support your business objectives.' },
]

export const clients = [
  'Entrepreneurs',
  'Founders',
  'CEOs',
  'Professionals',
  'Consultants',
  'Doctors',
  'Coaches',
  'Trainers',
  'Creators',
  'Influencers',
  'Startups',
  'SMEs',
  'Corporate Brands',
  'Public Personalities',
]

export const projects = [
  {
    name: 'Aarav Kapoor',
    industry: 'Founder / Fintech',
    category: 'Personal Branding',
    image: '/images/portrait-founder.jpg',
    challenge: 'Strong product, weak personal authority in a crowded founder market.',
    solution: 'Positioned Aarav as a category thinker with a signature narrative, LinkedIn system, and media-ready profile.',
    services: 'Personal Branding + LinkedIn + Media Profile',
    result: '3.2× profile views and a consistent inbound pipeline from investors and partners.',
  },
  {
    name: 'Nourish Atelier',
    industry: 'Wellness Brand',
    category: 'PR',
    image: '/images/pr-stage.jpg',
    challenge: 'Premium product with almost no earned media or founder visibility.',
    solution: 'Built a founder-led PR calendar, press kit, and launch announcements around a seasonal campaign.',
    services: 'PR + Brand Positioning + Event PR',
    result: 'National lifestyle coverage and a 40% lift in branded search during launch month.',
  },
  {
    name: 'Dr. Meera Iyer',
    industry: 'Healthcare',
    category: 'Websites',
    image: '/images/web-mockup.jpg',
    challenge: 'Clinic looked generic online, so high-intent patients bounced to competitors.',
    solution: 'Designed a calm, conversion-led personal brand website with clear services and enquiry paths.',
    services: 'Website + Personal Branding + Content',
    result: '2.8× enquiry form completions within 90 days of launch.',
  },
  {
    name: 'Studio North',
    industry: 'Architecture',
    category: 'Video',
    image: '/images/video-set.jpg',
    challenge: 'Beautiful work that never travelled beyond a quiet Instagram grid.',
    solution: 'Shot and edited a cinematic brand film plus a short-form content engine for reels.',
    services: 'Video + Social + Brand Story',
    result: 'Reels average view time doubled; two flagship project leads attributed to the film.',
  },
  {
    name: 'Kite & Co.',
    industry: 'D2C Fashion',
    category: 'Social Media',
    image: '/images/social-flatlay.jpg',
    challenge: 'Inconsistent creative and ads that looked busy but did not convert.',
    solution: 'Rebuilt the content system, campaign creatives, and a performance loop around best-selling SKUs.',
    services: 'Social Media + Meta Ads + Creative',
    result: 'CAC reduced 27% while branded engagement grew across Instagram and Meta.',
  },
  {
    name: 'Vikram Rao',
    industry: 'Executive Coach',
    category: 'Campaigns',
    image: '/images/portrait-creator.jpg',
    challenge: 'Expertise trapped in private rooms, with no public proof of thought leadership.',
    solution: 'A 90-day authority campaign: keynotes clips, founder PR, and a landing page for flagship programs.',
    services: 'Personal Branding + Video + Campaigns',
    result: 'Waitlist filled for two cohort programs without a cold-outreach sprint.',
  },
]

export const caseStudies = [
  {
    slug: 'founder-authority',
    name: 'Aarav Kapoor',
    title: 'From invisible founder to category voice',
    image: '/images/portrait-founder.jpg',
    challenge: 'The client needed stronger online visibility and professional positioning.',
    strategy:
      'We developed their brand positioning, social media strategy, website, and digital content — with personal branding as the centre of gravity.',
    delivered: 'Personal Branding + Website + Social Media + Video Content',
    results: [
      { k: '3.2×', l: 'Profile reach growth' },
      { k: '18k', l: 'New qualified followers' },
      { k: '64', l: 'Inbound leads generated' },
      { k: '4', l: 'Media features secured' },
    ],
  },
  {
    slug: 'clinic-presence',
    name: 'Dr. Meera Iyer',
    title: 'A medical practice that finally looks as trusted as it is',
    image: '/images/web-mockup.jpg',
    challenge: 'Patients could not quickly understand expertise, specialisations, or how to book.',
    strategy:
      'We rebuilt identity, website architecture, and a calm content cadence that educates without sounding promotional.',
    delivered: 'Personal Branding + Website + Content Strategy',
    results: [
      { k: '2.8×', l: 'Website enquiry growth' },
      { k: '41%', l: 'Lower bounce rate' },
      { k: '12', l: 'Thought-leadership pieces' },
      { k: '9.4', l: 'Avg. review score lift' },
    ],
  },
  {
    slug: 'brand-film',
    name: 'Studio North',
    title: 'A film that made craft feel inevitable',
    image: '/images/video-set.jpg',
    challenge: 'The studio’s work was exceptional, but the brand felt quiet and interchangeable online.',
    strategy:
      'We paired a cinematic brand story with a repeatable short-form editing system for project reveals.',
    delivered: 'Video Production + Social + Brand Story',
    results: [
      { k: '2×', l: 'Average view time' },
      { k: '1.6M', l: 'Campaign reach' },
      { k: '2', l: 'Flagship project leads' },
      { k: '35%', l: 'Engagement improvement' },
    ],
  },
]

export const testimonials = [
  {
    name: 'Aarav Kapoor',
    role: 'Founder, Helios Pay',
    image: '/images/portrait-founder.jpg',
    quote:
      'DELIBOT did not just “do social.” They built a narrative I could actually own — in rooms, on stage, and on LinkedIn.',
  },
  {
    name: 'Ishaan Varghese',
    role: 'Managing Partner, Northline',
    image: '/images/portrait-consultant.jpg',
    quote:
      'The PR work felt precise. Fewer vanity mentions, more of the right conversations with the right people.',
  },
  {
    name: 'Vikram Rao',
    role: 'Executive Coach',
    image: '/images/portrait-creator.jpg',
    quote:
      'They understood that my brand had to sound like me. The content finally matches the work I do in the room.',
  },
]

export const posts = [
  {
    slug: 'why-every-founder-needs-a-personal-brand',
    title: 'Why Every Founder Needs a Personal Brand',
    category: 'Personal Branding',
    date: '18 Sep 2026',
    image: '/images/portrait-founder.jpg',
    excerpt: 'Investors, talent, and customers decide faster when they trust the person behind the product.',
    body: [
      'A company brand can be admired. A founder brand is believed. In a noisy market, people still buy certainty — and certainty is easier to feel when a real person stands behind the work.',
      'Personal branding is not a vanity project. It is a distribution system for your point of view: how you frame problems, how you make decisions, and why your company exists.',
      'DELIBOT helps founders turn expertise into a repeatable presence — positioning, content, media, and a digital home that all say the same thing.',
    ],
  },
  {
    slug: 'personal-branding-generates-business',
    title: 'How Personal Branding Helps Generate Business',
    category: 'Brand Building',
    date: '04 Sep 2026',
    image: '/images/about-studio.jpg',
    excerpt: 'When your story is clear, sales conversations start warmer and close faster.',
    body: [
      'Most professionals already have proof. What they lack is a public, consistent story that makes that proof easy to find.',
      'A well-built personal brand reduces friction: people arrive pre-sold on your values, your process, and your taste. Enquiries become more qualified because the wrong-fit audience self-selects out.',
      'We design branding systems that feed business development — not just aesthetics.',
    ],
  },
  {
    slug: 'pr-vs-advertising',
    title: 'PR vs Advertising: What’s the Difference?',
    category: 'Public Relations',
    date: '21 Aug 2026',
    image: '/images/pr-stage.jpg',
    excerpt: 'Advertising buys attention. PR earns belief. Ambitious brands need both — sequenced well.',
    body: [
      'Advertising is a megaphone you rent. PR is a reputation you keep. One is excellent at reach. The other is excellent at trust.',
      'The mistake is treating PR like unpaid ads, or ads like a substitute for credibility. DELIBOT builds a spine of story first, then uses paid amplification where it actually compounds.',
    ],
  },
  {
    slug: 'improve-linkedin-personal-brand',
    title: '10 Ways to Improve Your LinkedIn Personal Brand',
    category: 'Personal Branding',
    date: '08 Aug 2026',
    image: '/images/social-flatlay.jpg',
    excerpt: 'LinkedIn rewards clarity, consistency, and a point of view — not a résumé dump.',
    body: [
      'Start with positioning, not posting. If the headline, banner, and about section do not say who you help and why you are different, content will not save you.',
      'Then build a cadence: signature themes, proof, and perspective. We help professionals design that system so LinkedIn becomes an asset instead of a chore.',
    ],
  },
  {
    slug: 'why-your-business-needs-a-website',
    title: 'Why Your Business Needs a Professional Website',
    category: 'Website Strategy',
    date: '19 Jul 2026',
    image: '/images/web-mockup.jpg',
    excerpt: 'Social media is rented land. Your website is where trust, narrative, and conversion meet.',
    body: [
      'When someone is seriously considering you, they look for a place that feels considered. A website is still that place.',
      'We design sites that carry brand, story, and a clear next step — fast, mobile-first, and built to convert rather than merely exist.',
    ],
  },
  {
    slug: 'short-form-video-brands',
    title: 'Short-Form Video: Why Brands Cannot Ignore It',
    category: 'Video Marketing',
    date: '02 Jul 2026',
    image: '/images/video-set.jpg',
    excerpt: 'Attention is won in seconds. Memory is won with craft. Short-form can do both.',
    body: [
      'Reels and shorts are not a trend to “try.” They are the current default language of discovery.',
      'DELIBOT treats short-form as branded filmmaking at speed: concept, edit, story, and a look that still feels premium when it is three inches wide.',
    ],
  },
]
